-- Your SQL goes here
CREATE TABLE gigs (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name VARCHAR NOT NULL,
  location VARCHAR NOT NULL,
  date_start VARCHAR NOT NULL,
  date_end VARCHAR NOT NULL,
  notes TEXT NOT NULL,
  admin_secret VARCHAR NOT NULL,
  show_private INTEGER NOT NULL DEFAULT 0,
  default_gig INTEGER NOT NULL DEFAULT 0
)
